#Cadastro do usuário (administrador), deve retornar um status code 200 com o código do usuário. Em caso de falha, deve retornar um status code 400 com a mensagem de erro.

POST http://localhost:3333/admin
Content-Type: application/json

{
    "nome" : "Nome Completo",
    "email" : "email@email.com",
    "senha" : "12345678",
    "cpf" : "123.456.789-99"
}